<?php


// Translation of file /modules/settings/template/css.php

$_COS_LANG_MODULE['Edit Template Css'] = 'Stilark';
$_COS_LANG_MODULE['settings_css_updated'] = 'Stilark opdateret';

// Translation of file /modules/settings/template/index.php

$_COS_LANG_MODULE['Edit Template'] = 'Ret template';
$_COS_LANG_MODULE['settings_template_updated'] = 'Template opdateret';

// Translation of file /modules/settings/template/views.php

$_COS_LANG_MODULE['Select template'] = 'Vælg template';
$_COS_LANG_MODULE['Update'] = 'Opdater';
$_COS_LANG_MODULE['Edit Stylesheet'] = 'Ret Stylesheet';
$_COS_LANG_MODULE['Select Stylesheet'] = 'Vælg Stylesheet';

// Translation of file /modules/settings/menu/module.php

$_COS_LANG_MODULE['Only unique values allowed for every menu item'] = 'Kun unikke værdier kan sættes for menu indstillingerne';

// Translation of file /modules/settings/menu/titles.php

$_COS_LANG_MODULE['settings_menu_titles_updated'] = 'Menu titler opdateret';

// Translation of file /modules/settings/menu/index.php

$_COS_LANG_MODULE['Menus'] = 'Menuer';

// Translation of file /modules/settings/menu/order.php

$_COS_LANG_MODULE['Menu Order'] = 'Menu rækkefølge';

// Translation of file /modules/settings/index.php

$_COS_LANG_MODULE['Site Settings'] = 'Webside Indstillinger';
$_COS_LANG_MODULE["Sentence with a strange char 'this'"] = "Sætning med en mærkelig char 'dette'";

// Translation of file /modules/settings/favicon/index.php

$_COS_LANG_MODULE['settings_favicon_title'] = 'Favicon';

// Translation of file /modules/settings/logo/index.php

$_COS_LANG_MODULE['Edit Logo'] = 'Rediger Logo';

// Translation of file /modules/settings/lib/image_form.inc

$_COS_LANG_MODULE['settings_upload_no_file_specified'] = 'Ingen Fil valgt';
$_COS_LANG_MODULE['settings_upload_wrong_filetype_specified'] = 'Forkert fil type. Følgende kan benyttes: ';
$_COS_LANG_MODULE['settings_image_updated'] = 'Billede blev uploadet og opdateret';
$_COS_LANG_MODULE['settings_image_deleted'] = 'Billede blev slettet';
$_COS_LANG_MODULE['settings_label_file'] = 'Fil';
$_COS_LANG_MODULE['settings_legend_delete'] = 'Slet fil';

// Translation of file /modules/settings/text/index.php

$_COS_LANG_MODULE['Set Misc Settings'] = 'Opdater diverse';
$_COS_LANG_MODULE['New settings has been saved'] = 'Indstillingerne er blevet opdateret';

// Translation of file /modules/settings/text/view.text.inc

$_COS_LANG_MODULE['Edit Misc Settings'] = 'Rediger diverse indstillinger';
$_COS_LANG_MODULE['Footer Message'] = 'Rediger side foden ';
$_COS_LANG_MODULE['Description'] = 'Site beskrivelse';

// Translation of file /modules/settings/mail/module.php

$_COS_LANG_MODULE['settings: error: not a valid mail method'] = 'Ingen gyldig mail metode';
$_COS_LANG_MODULE['settings: error: all smtp params needs to be set'] = 'Alle SMTP indstillinger skal angives';
$_COS_LANG_MODULE['settings: mail method legend'] = 'Vælg mail metode';
$_COS_LANG_MODULE['settings: mail label type'] = 'Mail metode';
$_COS_LANG_MODULE['settings: mail smtp legend'] = 'Indstil SMTP';
$_COS_LANG_MODULE['settings: label mail smtp host'] = 'Host';
$_COS_LANG_MODULE['settings: label mail smtp port'] = 'Port';
$_COS_LANG_MODULE['settings: label mail smtp username'] = 'Brugernavn';
$_COS_LANG_MODULE['settings: label mail smtp password'] = 'Password';
$_COS_LANG_MODULE['settings: label mail smtp auth'] = 'Auth (som regel true eller false) - men kan også være fx login';
$_COS_LANG_MODULE['settings: label mail sendmail path'] = 'Sti til sendmail program';
$_COS_LANG_MODULE['settings: label mail sendmail args'] = 'Argumenter til sendmail';
$_COS_LANG_MODULE['settings: mail php legend'] = 'Indtil PHP mail function';
$_COS_LANG_MODULE['settings: label mail php params'] = 'Angiv parameter til mail function';
$_COS_LANG_MODULE['settings: mail email system legend'] = 'Indstil system email';
$_COS_LANG_MODULE['settings: label mail system site email'] = 'System email, primært email adresse';

// Translation of file /modules/settings/mail/system.php

$_COS_LANG_MODULE['settings: action message: site email updated'] = 'Site email er opdateret';

// Translation of file /modules/settings/mail/index.php

$_COS_LANG_MODULE['settings: action message: mail method updated'] = 'Mail metode er opdateret';

// Translation of file /modules/settings/mail/params.php

$_COS_LANG_MODULE['settings: mail current method is'] = 'Nuværende mail metode er: ';
$_COS_LANG_MODULE['settings: action message: smtp updated'] = 'SMTP indstillinger blev opdateret';
$_COS_LANG_MODULE['settings: action message: sendmail updated'] = 'Sendmail indstilling blev opdateret';
