<?php

/**
 * Language file for module settings
 *
 * @package     settings
 */
$_COS_LANG_MODULE['settings'] = 'Indstillinger';

#settings
$_COS_LANG_MODULE['Site Settings'] = 'Webside Indstillinger';
$_COS_LANG_MODULE['Change Logo']= 'Logo';
$_COS_LANG_MODULE['Set footer message'] = 'Rediger side foden';
$_COS_LANG_MODULE['Set template'] = 'Template';
$_COS_LANG_MODULE['Settings'] = 'Indstillinger';
$_COS_LANG_MODULE['Modules'] = 'Moduler';
$_COS_LANG_MODULE['List Modules'] = 'List Moduler';
$_COS_LANG_MODULE['Menu Order'] = 'Menu rækkefølge';
$_COS_LANG_MODULE['Core modules'] = 'Kerne moduler';
$_COS_LANG_MODULE['error'] = 'Fejl';

$_COS_LANG_MODULE['Determine order of menus'] = 'Ret menuer';
$_COS_LANG_MODULE['Only unique values allowed for every module'] = 'Kun unikke værdier er tilladt som vægt';
$_COS_LANG_MODULE['Edit Misc Settings'] = 'Rediger diverse indstillinger';
$_COS_LANG_MODULE['Site Email'] = 'Sidens email';
$_COS_LANG_MODULE['Footer Message'] = 'Rediger side foden ';
$_COS_LANG_MODULE['New settings has been saved'] = 'Indstillingerne er blevet opdateret';
$_COS_LANG_MODULE['Edit Logo'] = 'Rediger Logo';
$_COS_LANG_MODULE['Logo file'] = 'Logo fil';
$_COS_LANG_MODULE['Edit Template'] = 'Rediger template';
$_COS_LANG_MODULE['Template Updated'] = 'Template opdateret';
$_COS_LANG_MODULE['Edit Template'] = 'Ret template';
$_COS_LANG_MODULE['Select template'] = 'Vælg template';

$_COS_LANG_MODULE['$_MAIN_MENU_ITEM not defined in: '] = '$_MAIN_MENU_ITEM er ikke defineret i: ';
$_COS_LANG_MODULE['Main Menu'] = 'Main Menu';
$_COS_LANG_MODULE['Delete Logo'] = 'Slet Logo';
$_COS_LANG_MODULE['Delete Current Logo'] = 'Slet nuværende logo';
$_COS_LANG_MODULE['Only unique values allowed for every menu item'] = 'Kun unikke værdier kan sættes for menu indstillingerne';

$_COS_LANG_MODULE['Description'] = 'Site beskrivelse';

$_COS_LANG_MODULE['Set Misc Settings'] = 'Opdater diverse';

$_COS_LANG_MODULE['Menus'] = 'Menuer';
$_COS_LANG_MODULE['settings_menu_titles_updated'] = 'Menu titler opdateret';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stilark';
$_COS_LANG_MODULE['settings_css_updated'] = 'Stilark opdateret';

$_COS_LANG_MODULE['Edit Stylesheet'] = 'Ret Stylesheet';
$_COS_LANG_MODULE['Select Stylesheet'] = 'Vælg Stylesheet';
$_COS_LANG_MODULE['Update'] = 'Opdater';

$_COS_LANG_MODULE['settings_upload_no_file_specified'] = 'Ingen Fil valgt';
$_COS_LANG_MODULE['settings_upload_wrong_filetype_specified'] = 'Forkert fil type. Følgende kan benyttes: ';

$_COS_LANG_MODULE['settings_favicon_title'] = 'Favicon';

$_COS_LANG_MODULE['settings_label_file'] = 'Fil';
$_COS_LANG_MODULE['settings_legend_delete'] = 'Slet fil';

$_COS_LANG_MODULE['settings_meta_in_visible_for_robots'] = 'Siden skal ikke indekseres af robotter';
$_COS_LANG_MODULE['settings_meta_visible_for_robots'] = 'Siden indekseres af robotter';
$_COS_LANG_MODULE['settings_robots_legend'] = 'Synlighed overfor robotter';

$_COS_LANG_MODULE['settings_meta_updated_action'] = 'Meta tags opdateret';
