<?php

/**
 * Language file for module settings
 *
 * @package     settings
 */
$_COS_LANG_MODULE['Settings'] = 'Indstillinger';

$_COS_LANG_MODULE['settings_menu_title'] = 'Titler';

$_COS_LANG_MODULE['Unenabled Menus. Check to enable'] = 'Unenabled Menus. Check to enable';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Enabled Menus. Check to disable';
$_COS_LANG_MODULE['Submit'] = 'Send';
$_COS_LANG_MODULE['Core menus'] = 'Core menus';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Vælg menu titler';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Template Style'] = 'Template Style';
$_COS_LANG_MODULE['settings_looks'] = 'Template og Logo';

