<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System email';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metode';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Indstil mail metode';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Skabelon og Css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Mail';
$_COS_LANG_MODULE['settings'] = 'Indstillinger';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Set template'] = 'Template';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stilark';
