<?php


// Translation of file /modules/settings/template/menu.inc

$_COS_LANG_MODULE['Set template'] = 'Template';
$_COS_LANG_MODULE['Template Style'] = 'Template Style';

// Translation of file /modules/settings/install.inc

$_COS_LANG_MODULE['settings_looks'] = 'Template';
$_COS_LANG_MODULE['settings_mail'] = 'Mail';

// Translation of file /modules/settings/menu/view.menu.inc

$_COS_LANG_MODULE['Determine order of menus'] = 'Ret menuer';
$_COS_LANG_MODULE['Submit'] = 'Send';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Enabled Menus. Check to disable';
$_COS_LANG_MODULE['Core menus'] = 'Core menus';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Vælg menu titler';
$_COS_LANG_MODULE['Update'] = 'Opdater';

// Translation of file /modules/settings/menu/menu.inc

$_COS_LANG_MODULE['Menu Order'] = 'Menu rækkefølge';
$_COS_LANG_MODULE['settings_menu_title'] = 'Titler';

// Translation of file /modules/settings/menu.inc

$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stilark';

// Translation of file /modules/settings/mail/menu.inc

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System email';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metode';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Indstil mail metode';
