<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = '邮件系统';
$_COS_LANG_MODULE['settings: menu mail method'] = '邮件的方法';
$_COS_LANG_MODULE['settings: menu mail params'] = '邮件PARAMS';
$_COS_LANG_MODULE['Menu: settings_looks'] = '模板和CSS';
$_COS_LANG_MODULE['Menu: settings_mail'] = '邮件';
$_COS_LANG_MODULE['settings'] = '设置';
$_COS_LANG_MODULE['Change Logo'] = '标志';
$_COS_LANG_MODULE['settings_menu_favicon'] = '网站图标';
$_COS_LANG_MODULE['Set template'] = '模板';
$_COS_LANG_MODULE['Edit Template Css'] = 'Sylesheet';
