<?php

$_COS_LANG_MODULE['Set template'] = '模板';
$_COS_LANG_MODULE['Template Style'] = '模板风格';
$_COS_LANG_MODULE['settings: menu mail system mail'] = '邮件系统';
$_COS_LANG_MODULE['settings: menu mail method'] = '邮件的方法';
$_COS_LANG_MODULE['settings: menu mail params'] = '邮件PARAMS';
$_COS_LANG_MODULE['Menu Order'] = '菜单顺序';
$_COS_LANG_MODULE['settings_menu_title'] = '主菜单标题';
$_COS_LANG_MODULE['Determine order of menus'] = '为了确定菜单';
$_COS_LANG_MODULE['Submit'] = '提交';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = '启用菜单。点击进入空时禁用';
$_COS_LANG_MODULE['Core menus'] = '核心菜单';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = '编辑主菜单标题';
$_COS_LANG_MODULE['Update'] = '更新';
$_COS_LANG_MODULE['Menu: settings_looks'] = '模板和CSS';
$_COS_LANG_MODULE['Menu: settings_mail'] = '邮件';
$_COS_LANG_MODULE['Change Logo'] = '标志';
$_COS_LANG_MODULE['settings_menu_favicon'] = '网站图标';
$_COS_LANG_MODULE['Edit Template Css'] = 'Sylesheet';
