<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = '邮件系统';
$_COS_LANG_MODULE['settings: menu mail method'] = '邮件的方法';
$_COS_LANG_MODULE['settings: menu mail params'] = '邮件PARAMS';
$_COS_LANG_MODULE['Look and feel'] = '外观和感觉';
$_COS_LANG_MODULE['SMTP Mail'] = 'SMTP邮件';
$_COS_LANG_MODULE['settings'] = '设置';
$_COS_LANG_MODULE['Change Logo'] = '标志';
$_COS_LANG_MODULE['Change favicon'] = '更改图标';
$_COS_LANG_MODULE['Set template'] = '模板';
$_COS_LANG_MODULE['Edit Template Css'] = 'Sylesheet';
