<?php


// Translation of file /modules/settings/template/module.php

$_COS_LANG_MODULE['Edit Template'] = 'Edit Template';
$_COS_LANG_MODULE['settings_template_updated'] = 'settings_template_updated';
$_COS_LANG_MODULE['Edit Template Css'] = 'Edit Template Css';
$_COS_LANG_MODULE['settings_css_updated'] = 'settings_css_updated';
$_COS_LANG_MODULE['Select a template'] = 'Select a template';

// Translation of file /modules/settings/template/views.php

$_COS_LANG_MODULE['Select template'] = 'Select template';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Edit Stylesheet'] = 'Edit Stylesheet';
$_COS_LANG_MODULE['Select Stylesheet'] = 'Select Stylesheet';

// Translation of file /modules/settings/module.php

$_COS_LANG_MODULE['Site Settings'] = 'Site Settings';

// Translation of file /modules/settings/mail/module.php

$_COS_LANG_MODULE['settings: action message: mail method updated'] = 'settings: action message: mail method updated';
$_COS_LANG_MODULE['settings: action message: smtp updated'] = 'settings: action message: smtp updated';
$_COS_LANG_MODULE['settings: action message: sendmail updated'] = 'settings: action message: sendmail updated';
$_COS_LANG_MODULE['settings: action message: site email updated'] = 'settings: action message: site email updated';
$_COS_LANG_MODULE['settings: error: not a valid mail method'] = 'settings: error: not a valid mail method';
$_COS_LANG_MODULE['settings: error: all smtp params needs to be set'] = 'settings: error: all smtp params needs to be set';
$_COS_LANG_MODULE['settings: mail method legend'] = 'settings: mail method legend';
$_COS_LANG_MODULE['settings: mail label type'] = 'settings: mail label type';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['settings: mail smtp legend'] = 'settings: mail smtp legend';
$_COS_LANG_MODULE['settings: label mail smtp host'] = 'settings: label mail smtp host';
$_COS_LANG_MODULE['settings: label mail smtp port'] = 'settings: label mail smtp port';
$_COS_LANG_MODULE['settings: label mail smtp username'] = 'settings: label mail smtp username';
$_COS_LANG_MODULE['settings: label mail smtp password'] = 'settings: label mail smtp password';
$_COS_LANG_MODULE['settings: label mail smtp auth'] = 'settings: label mail smtp auth';
$_COS_LANG_MODULE['settings: label mail sendmail path'] = 'settings: label mail sendmail path';
$_COS_LANG_MODULE['settings: label mail sendmail args'] = 'settings: label mail sendmail args';
$_COS_LANG_MODULE['submit'] = 'submit';
$_COS_LANG_MODULE['settings: mail php legend'] = 'settings: mail php legend';
$_COS_LANG_MODULE['settings: label mail php params'] = 'settings: label mail php params';
$_COS_LANG_MODULE['settings: mail email system legend'] = 'settings: mail email system legend';
$_COS_LANG_MODULE['settings: label mail system site email'] = 'settings: label mail system site email';

// Translation of file /modules/settings/logo/module.php

$_COS_LANG_MODULE['Edit Logo'] = 'Edit Logo';

// Translation of file /modules/settings/background/module.php

$_COS_LANG_MODULE['settings_favicon_title'] = 'settings_favicon_title';

// Translation of file /modules/settings/favicon/module.php


// Translation of file /modules/settings/lib/image_form.php

$_COS_LANG_MODULE['settings_upload_no_file_specified'] = 'settings_upload_no_file_specified';
$_COS_LANG_MODULE['settings_upload_wrong_filetype_specified'] = 'settings_upload_wrong_filetype_specified';
$_COS_LANG_MODULE['Image updated'] = 'Image updated';
$_COS_LANG_MODULE['Image deleted'] = 'Image deleted';
$_COS_LANG_MODULE['Update image'] = 'Update image';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['Delete'] = 'Delete';
