<?php


// Translation of file /modules/settings/template/module.php

$_COS_LANG_MODULE['Edit Template'] = 'Edit Template';
$_COS_LANG_MODULE['settings_template_updated'] = 'Template updated';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
$_COS_LANG_MODULE['settings_css_updated'] = 'Stylesheet updated';
$_COS_LANG_MODULE['Select a template'] = 'Select a template';

// Translation of file /modules/settings/template/views.php

$_COS_LANG_MODULE['Select template'] = 'Select template';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Edit Stylesheet'] = 'Edit Stylesheet';
$_COS_LANG_MODULE['Select Stylesheet'] = 'Select Stylesheet';

// Translation of file /modules/settings/module.php

$_COS_LANG_MODULE['Site Settings'] = 'Site Settings';

// Translation of file /modules/settings/mail/module.php

$_COS_LANG_MODULE['settings: action message: mail method updated'] = 'Mail method updated';
$_COS_LANG_MODULE['settings: action message: smtp updated'] = 'SMTP settings updated';
$_COS_LANG_MODULE['settings: action message: sendmail updated'] = 'Sendmail settings updated';
$_COS_LANG_MODULE['settings: action message: site email updated'] = 'System email has been updated';
$_COS_LANG_MODULE['settings: error: not a valid mail method'] = 'Not a valid mail method';
$_COS_LANG_MODULE['settings: error: all smtp params needs to be set'] = 'All SMTP params needs to be set';
$_COS_LANG_MODULE['settings: mail method legend'] = 'Set system mail method';
$_COS_LANG_MODULE['settings: mail label type'] = 'Choose method - needs to be supported by your system';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['settings: mail smtp legend'] = 'SMTP settings';
$_COS_LANG_MODULE['settings: label mail smtp host'] = 'Host';
$_COS_LANG_MODULE['settings: label mail smtp port'] = 'Port';
$_COS_LANG_MODULE['settings: label mail smtp username'] = 'Username';
$_COS_LANG_MODULE['settings: label mail smtp password'] = 'Password';
$_COS_LANG_MODULE['settings: label mail smtp auth'] = 'Auth (true or false) - but can also be e.g. login';
$_COS_LANG_MODULE['settings: label mail sendmail path'] = 'Path to sendmail';
$_COS_LANG_MODULE['settings: label mail sendmail args'] = 'Args to sendmail';
$_COS_LANG_MODULE['submit'] = 'submit';
$_COS_LANG_MODULE['settings: mail php legend'] = 'Set PHP mail settings - often you do not need to do anything';
$_COS_LANG_MODULE['settings: label mail php params'] = 'PHP mail function params';
$_COS_LANG_MODULE['settings: mail email system legend'] = 'Set system email';
$_COS_LANG_MODULE['settings: label mail system site email'] = 'Set system email';

// Translation of file /modules/settings/logo/module.php

$_COS_LANG_MODULE['Edit Logo'] = 'Edit Logo';

// Translation of file /modules/settings/background/module.php

$_COS_LANG_MODULE['settings_favicon_title'] = 'Favicon';

// Translation of file /modules/settings/favicon/module.php


// Translation of file /modules/settings/lib/image_form.php

$_COS_LANG_MODULE['settings_upload_no_file_specified'] = 'Please select a file';
$_COS_LANG_MODULE['settings_upload_wrong_filetype_specified'] = 'Wrong file type. Only these are allowed: ';
$_COS_LANG_MODULE['Image updated'] = 'Image updated';
$_COS_LANG_MODULE['Image deleted'] = 'Image deleted';
$_COS_LANG_MODULE['Update image'] = 'Update image';
$_COS_LANG_MODULE['Delete image'] = 'Delete image';
$_COS_LANG_MODULE['Delete'] = 'Delete';
