<?php


// Translation of file /modules/settings/template/css.php

$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
$_COS_LANG_MODULE['settings_css_updated'] = 'Stylesheet updated';

// Translation of file /modules/settings/template/views.php

$_COS_LANG_MODULE['Edit Template'] = 'Edit Template';
$_COS_LANG_MODULE['Select template'] = 'Select template';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Edit Stylesheet'] = 'Edit Stylesheet';
$_COS_LANG_MODULE['Select Stylesheet'] = 'Select Stylesheet';

// Translation of file /modules/settings/template/index.php

$_COS_LANG_MODULE['settings_template_updated'] = 'Template updated';

// Translation of file /modules/settings/template/module.php

$_COS_LANG_MODULE['Select a template'] = 'Select a template';

// Translation of file /modules/settings/background/index.php

$_COS_LANG_MODULE['settings_favicon_title'] = 'Favicon';

// Translation of file /modules/settings/mail/params.php

$_COS_LANG_MODULE['settings: mail current method is'] = 'Current mail method is: ';
$_COS_LANG_MODULE['settings: action message: smtp updated'] = 'SMTP settings updated';
$_COS_LANG_MODULE['settings: action message: sendmail updated'] = 'Sendmail settings updated';

// Translation of file /modules/settings/mail/index.php

$_COS_LANG_MODULE['settings: action message: mail method updated'] = 'Mail method updated';

// Translation of file /modules/settings/mail/module.php

$_COS_LANG_MODULE['settings: error: not a valid mail method'] = 'Not a valid mail method';
$_COS_LANG_MODULE['settings: error: all smtp params needs to be set'] = 'All SMTP params needs to be set';
$_COS_LANG_MODULE['settings: mail method legend'] = 'Set system mail method';
$_COS_LANG_MODULE['settings: mail label type'] = 'Choose method - needs to be supported by your system';
$_COS_LANG_MODULE['settings: mail smtp legend'] = 'SMTP settings';
$_COS_LANG_MODULE['settings: label mail smtp host'] = 'Host';
$_COS_LANG_MODULE['settings: label mail smtp port'] = 'Port';
$_COS_LANG_MODULE['settings: label mail smtp username'] = 'Username';
$_COS_LANG_MODULE['settings: label mail smtp password'] = 'Password';
$_COS_LANG_MODULE['settings: label mail smtp auth'] = 'Auth (true or false) - but can also be e.g. login';
$_COS_LANG_MODULE['settings: label mail sendmail path'] = 'Path to sendmail';
$_COS_LANG_MODULE['settings: label mail sendmail args'] = 'Args to sendmail';
$_COS_LANG_MODULE['settings: mail php legend'] = 'Set PHP mail settings - often you do not need to do anything';
$_COS_LANG_MODULE['settings: label mail php params'] = 'PHP mail function params';
$_COS_LANG_MODULE['settings: mail email system legend'] = 'Set system email';
$_COS_LANG_MODULE['settings: label mail system site email'] = 'Set system email';

// Translation of file /modules/settings/mail/system.php

$_COS_LANG_MODULE['settings: action message: site email updated'] = 'System email has been updated';

// Translation of file /modules/settings/menu/order.php

$_COS_LANG_MODULE['Menu Order'] = 'Menu Order';

// Translation of file /modules/settings/menu/titles.php

$_COS_LANG_MODULE['settings_menu_titles_updated'] = 'Menu titles has been updated';

// Translation of file /modules/settings/menu/index.php

$_COS_LANG_MODULE['Menus'] = 'Menus';

// Translation of file /modules/settings/menu/module.php

$_COS_LANG_MODULE['Only unique values allowed for every menu item'] = 'Only unique values allowed for every menu item';

// Translation of file /modules/settings/lib/image_form.inc

$_COS_LANG_MODULE['settings_upload_no_file_specified'] = 'Please select a file';
$_COS_LANG_MODULE['settings_upload_wrong_filetype_specified'] = 'Wrong file type. Only these are allowed: ';
$_COS_LANG_MODULE['Edit Logo'] = 'Edit Logo';
$_COS_LANG_MODULE['settings_image_updated'] = 'Image uploaded and updated';
$_COS_LANG_MODULE['settings_image_deleted'] = 'Image deleted';
$_COS_LANG_MODULE['settings_label_file'] = 'File';
$_COS_LANG_MODULE['settings_legend_delete'] = 'Delete file';

// Translation of file /modules/settings/text/view.text.inc

$_COS_LANG_MODULE['Edit Misc Settings'] = 'Edit Misc Settings';
$_COS_LANG_MODULE['Footer Message'] = 'Footer Message';
$_COS_LANG_MODULE['Description'] = 'Description';

// Translation of file /modules/settings/text/index.php

$_COS_LANG_MODULE['Set Misc Settings'] = 'Set Misc Settings';
$_COS_LANG_MODULE['New settings has been saved'] = 'New settings has been saved';

// Translation of file /modules/settings/logo/index.php


// Translation of file /modules/settings/index.php

$_COS_LANG_MODULE['Site Settings'] = 'Site Settings';

// Translation of file /modules/settings/favicon/index.php
