<?php


// Translation of file /modules/settings/mail/menu.inc

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'settings: menu mail system mail';
$_COS_LANG_MODULE['settings: menu mail method'] = 'settings: menu mail method';
$_COS_LANG_MODULE['settings: menu mail params'] = 'settings: menu mail params';

// Translation of file /modules/settings/install.inc

$_COS_LANG_MODULE['Look and feel'] = 'Look and feel';
$_COS_LANG_MODULE['SMTP Mail'] = 'SMTP Mail';

// Translation of file /modules/settings/system_lang.inc

$_COS_LANG_MODULE['settings'] = 'settings';

// Translation of file /modules/settings/menu.inc

$_COS_LANG_MODULE['Change Logo'] = 'Change Logo';
$_COS_LANG_MODULE['Change favicon'] = 'Change favicon';
$_COS_LANG_MODULE['Set template'] = 'Set template';
$_COS_LANG_MODULE['Edit Template Css'] = 'Edit Template Css';
