<?php


// Translation of file /modules/settings/mail/menu.inc

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System mail';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail method';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';

// Translation of file /modules/settings/install.inc

$_COS_LANG_MODULE['Menu: settings_looks'] = 'Template and css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Mail';

// Translation of file /modules/settings/system_lang.inc

$_COS_LANG_MODULE['settings'] = 'Settings';

// Translation of file /modules/settings/menu.inc

$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Set template'] = 'Template';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
