<?php


// Translation of file /modules/settings/template/menu.inc

$_COS_LANG_MODULE['Set template'] = 'Template';
$_COS_LANG_MODULE['Template Style'] = 'Template Style';

// Translation of file /modules/settings/install.inc

$_COS_LANG_MODULE['Menu: settings_looks'] = 'Template and Css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Mail';

// Translation of file /modules/settings/menu/view.menu.inc

$_COS_LANG_MODULE['Determine order of menus'] = 'Determine order of menus';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Enabled Menus. Check to disable';
$_COS_LANG_MODULE['Core menus'] = 'Core menus';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Edit main menu titles';
$_COS_LANG_MODULE['Update'] = 'Update';

// Translation of file /modules/settings/menu/menu.inc

$_COS_LANG_MODULE['Menu Order'] = 'Menu Order';
$_COS_LANG_MODULE['settings_menu_title'] = 'Main Menu title';

// Translation of file /modules/settings/menu.inc

$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Edit Template Css'] = 'Sylesheet';

// Translation of file /modules/settings/mail/menu.inc

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System mail';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail method';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
