<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System epost';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metode';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Sett mail metoden';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Mal og css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Mail';
$_COS_LANG_MODULE['settings'] = 'Innstillinger';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Set template'] = 'Mal';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stilark';
