<?php

$_COS_LANG_MODULE['Set template'] = 'Mal';
$_COS_LANG_MODULE['Template Style'] = 'Mal Stil';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Mal og css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Mail';
$_COS_LANG_MODULE['Determine order of menus'] = 'Redigere menyer';
$_COS_LANG_MODULE['Submit'] = 'Send';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Balanseført menyer. Ikke bruk anlegget tomt for å aktivere';
$_COS_LANG_MODULE['Core menus'] = 'Primære menyer';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Velg Menytitlene';
$_COS_LANG_MODULE['Update'] = 'Refresh';
$_COS_LANG_MODULE['Menu Order'] = 'Meny for';
$_COS_LANG_MODULE['settings_menu_title'] = 'Titler';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stilark';
$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System epost';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metode';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Sett mail metoden';
