<?php

$_COS_LANG_MODULE['Set template'] = 'Schablone';
$_COS_LANG_MODULE['Template Style'] = 'Template-Stil';
$_COS_LANG_MODULE['settings: menu mail system mail'] = 'Mail-System';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail-Verfahren';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
$_COS_LANG_MODULE['Menu Order'] = 'Menü bestellen';
$_COS_LANG_MODULE['settings_menu_title'] = 'Hauptmenü Titel';
$_COS_LANG_MODULE['Determine order of menus'] = 'Bestimmen der Reihenfolge der Menüs';
$_COS_LANG_MODULE['Submit'] = 'Einreichen';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Aktiviert Menüs. Klicken Sie auf und geben Sie leer zu deaktivieren';
$_COS_LANG_MODULE['Core menus'] = 'Core-Menüs';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Bearbeiten Hauptmenü Titel';
$_COS_LANG_MODULE['Update'] = 'Aktualisierung';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Template und CSS';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Post';
$_COS_LANG_MODULE['settings'] = 'Einstellungen';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
