<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'Mail-System';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail-Verfahren';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Template und CSS';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Post';
$_COS_LANG_MODULE['settings'] = 'Einstellungen';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Set template'] = 'Schablone';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
