<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'Mail-System';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail-Verfahren';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
$_COS_LANG_MODULE['Look and feel'] = 'Look and Feel';
$_COS_LANG_MODULE['SMTP Mail'] = 'SMTP-Mail-';
$_COS_LANG_MODULE['settings'] = 'Einstellungen';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['Change favicon'] = 'Favicon ändern';
$_COS_LANG_MODULE['Set template'] = 'Schablone';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
