<?php

/**
 * Language file for module settings
 *
 * @package     settings
 */
$_COS_LANG_MODULE['Settings'] = 'Settings';

#settings
$_COS_LANG_MODULE['Site Settings'] = 'Site Settings';
$_COS_LANG_MODULE['Change Logo']= 'Change Logo';
$_COS_LANG_MODULE['Set footer message'] = 'Set footer message';
$_COS_LANG_MODULE['Set template'] = 'Set template';
$_COS_LANG_MODULE['Settings'] = 'Settings';
$_COS_LANG_MODULE['Modules'] = 'Modules';
$_COS_LANG_MODULE['List Modules'] = 'List Modules';
$_COS_LANG_MODULE['Menu Order'] = 'Menu Order';
$_COS_LANG_MODULE['Core modules'] = 'Core modules';
$_COS_LANG_MODULE['content'] = 'Content';
$_COS_LANG_MODULE['error'] = 'error';

$_COS_LANG_MODULE['Unenabled Modules. Check to enable'] = 'Unenabled Modules. Check to enable';
$_COS_LANG_MODULE['Enabled Modules. Check to disable'] = 'Enabled Modules. Check to disable';
$_COS_LANG_MODULE['Determine order of menus'] = 'Determine order of menus';
$_COS_LANG_MODULE['Only unique values allowed for every module'] = 'Only unique values allowed for every module';
$_COS_LANG_MODULE['Edit Misc Settings'] = 'Edit Misc Settings';
$_COS_LANG_MODULE['Site Email'] = 'Site Email';
$_COS_LANG_MODULE['Footer Message'] = 'Footer Message';
$_COS_LANG_MODULE['New settings has been saved'] = 'New settings has been saved';
$_COS_LANG_MODULE['Edit Logo'] = 'Edit Logo';
$_COS_LANG_MODULE['Logo file'] = 'Logo file';
$_COS_LANG_MODULE['Edit Template'] = 'Edit Template';
$_COS_LANG_MODULE['Template Updated'] = 'Template Updated';
$_COS_LANG_MODULE['Edit Template'] = 'Edit Template';
$_COS_LANG_MODULE['Select template'] = 'Select template';

$_COS_LANG_MODULE['$_MAIN_MENU_ITEM not defined in: '] = '$_MAIN_MENU_ITEM not defined in: ';
$_COS_LANG_MODULE['Main Menu'] = 'Main Menu';
$_COS_LANG_MODULE['Delete Logo'] = 'Delete Logo';
$_COS_LANG_MODULE['Delete Current Logo'] = 'Delete Current Logo';
$_COS_LANG_MODULE['Only unique values allowed for every menu item'] = 'Only unique values allowed for every menu item';

$_COS_LANG_MODULE['Description'] = 'Description';

$_COS_LANG_MODULE['Template Style'] = 'Template Style';

$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Unenabled Menus. Check to enable'] = 'Unenabled Menus. Check to enable';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Enabled Menus. Check to disable';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Core menus'] = 'Core menus';


$_COS_LANG_MODULE['Menus'] = 'Menus';

$_COS_LANG_MODULE['Update'] = 'Update';

$_COS_LANG_MODULE['Set Misc Settings'] = 'Set Misc Settings';

$_COS_LANG_MODULE['Update'] = 'Update';



$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Edit Stylesheet'] = 'Edit Stylesheet';
$_COS_LANG_MODULE['Select Stylesheet'] = 'Select Stylesheet';
$_COS_LANG_MODULE['Update'] = 'Update';

$_COS_LANG_MODULE['Edit Template Css'] = 'Edit Template Css';
$_COS_LANG_MODULE['settings_css_updated'] = 'Stylesheet Updated';



$_COS_LANG_MODULE['settings_menu_titles_updated'] = 'Menu titles has been updated';
