<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System sähköposti';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail menetelmä';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Aseta mail menetelmä';
$_COS_LANG_MODULE['Look and feel'] = 'Katso ja koe';
$_COS_LANG_MODULE['SMTP Mail'] = 'SMTP Mail';
$_COS_LANG_MODULE['settings'] = 'Asetukset';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['Change favicon'] = 'Muuta favicon';
$_COS_LANG_MODULE['Set template'] = 'Sapluuna';
$_COS_LANG_MODULE['Edit Template Css'] = 'Tyylitaulukkoja';
