<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System sähköposti';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail menetelmä';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Aseta mail menetelmä';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Malli ja css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Posti';
$_COS_LANG_MODULE['settings'] = 'Asetukset';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Set template'] = 'Sapluuna';
$_COS_LANG_MODULE['Edit Template Css'] = 'Tyylitaulukkoja';
