<?php

$_COS_LANG_MODULE['Set template'] = 'Sapluuna';
$_COS_LANG_MODULE['Template Style'] = 'Malli Style';
$_COS_LANG_MODULE['Determine order of menus'] = 'Muokkaa valikoita';
$_COS_LANG_MODULE['Submit'] = 'Lähettää';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Aktivoidut valikot. Älä käytä laitos tyhjä aktivoida';
$_COS_LANG_MODULE['Core menus'] = 'Ensisijainen valikot';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Valitse valikossa otsikot';
$_COS_LANG_MODULE['Update'] = 'Virkistää';
$_COS_LANG_MODULE['Menu Order'] = 'Menu järjestyksessä';
$_COS_LANG_MODULE['settings_menu_title'] = 'Otsikot';
$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System sähköposti';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail menetelmä';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Aseta mail menetelmä';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Malli ja css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Posti';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Edit Template Css'] = 'Tyylitaulukkoja';
