<?php

$_COS_LANG_MODULE['Settings'] = 'Inställningar';
$_COS_LANG_MODULE['settings'] = 'Inställningar';
$_COS_LANG_MODULE['settings_menu_title'] = 'Huvudmeny titel';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Redigera huvudmenyn titlar';
$_COS_LANG_MODULE['settings_looks'] = 'Mall och logotyp';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['settings_meta_title'] = 'Metataggar';
$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System post';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metod';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
$_COS_LANG_MODULE['settings_mail'] = 'Mail';
