<?php

$_COS_LANG_MODULE['Set template'] = 'Mall';
$_COS_LANG_MODULE['Template Style'] = 'Template Style';
$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System post';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metod';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
$_COS_LANG_MODULE['Menu Order'] = 'Menu Order';
$_COS_LANG_MODULE['settings_menu_title'] = 'Huvudmeny titel';
$_COS_LANG_MODULE['Determine order of menus'] = 'Redigera menyer';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Enabled Menus. Check to disable'] = 'Enabled menyer. Kontrollera att inaktivera';
$_COS_LANG_MODULE['Core menus'] = 'Kärna menyer';
$_COS_LANG_MODULE['settings_menu_set_main_titles'] = 'Redigera huvudmenyn titlar';
$_COS_LANG_MODULE['Update'] = 'Update';
$_COS_LANG_MODULE['Menu: settings_looks'] = 'Mall och Css';
$_COS_LANG_MODULE['Menu: settings_mail'] = 'Mail';
$_COS_LANG_MODULE['settings'] = 'Inställningar';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['settings_menu_favicon'] = 'Favicon';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
