<?php

$_COS_LANG_MODULE['settings: menu mail system mail'] = 'System post';
$_COS_LANG_MODULE['settings: menu mail method'] = 'Mail metod';
$_COS_LANG_MODULE['settings: menu mail params'] = 'Mail params';
$_COS_LANG_MODULE['Look and feel'] = 'Utseende och känsla';
$_COS_LANG_MODULE['SMTP Mail'] = 'SMTP Mail';
$_COS_LANG_MODULE['settings'] = 'Inställningar';
$_COS_LANG_MODULE['Change Logo'] = 'Logo';
$_COS_LANG_MODULE['Change favicon'] = 'Ändra favikon';
$_COS_LANG_MODULE['Set template'] = 'Mall';
$_COS_LANG_MODULE['Edit Template Css'] = 'Stylesheet';
